site_name: CommandDotNet
site_description: Model your command line application interface in a class
repo_name: 'bilal-fazlani/commanddotnet'
repo_url: 'https://github.com/bilal-fazlani/commanddotnet'

strict: true

nav:
    - Documentation:
      - Introduction: index.md
      - features.md
      - getting-started.md
      - argument-terminology.md
      - Commands:
        - Commands/commands.md
        - Commands/subcommands.md
      - Arguments:
        - Arguments/arguments.md
        - Collections: Arguments/argument-collections.md
        - Data Types: Arguments/argument-types.md
        - Arguments/passwords.md 
        - Argument Models: Arguments/argument-models.md
        - Arguments/argument-arity.md
        - Arguments/option-or-operand.md
        - Arguments/fluent-validation-for-argument-models.md
      - Argument Values:
        - ArgumentValues/argument-separator.md
        - ArgumentValues/piped-arguments.md
        - ArgumentValues/prompting.md
        - ArgumentValues/response-files.md
        - AppSettings and<br/>Environment Variables: ArgumentValues/default-values-from-config.md
      - Help:
        - Help/help.md
        - Help/typo-suggestions.md
      - Diagnostics:
        - Diagnostics/app-version.md
        - Diagnostics/debug-directive.md
        - Diagnostics/parse-directive.md
        - Diagnostics/command-logger.md
        - Diagnostics/exceptions.md
      - Other Features:
        - OtherFeatures/default-middleware.md
        - Ctrl+C and<br/>CancellationToken: OtherFeatures/cancellation.md
        - OtherFeatures/dependency-injection.md
        - OtherFeatures/name-casing.md
        - OtherFeatures/newer-release-alerts.md
      - Extensibility:
        - Extensibility/directives.md
        - Extensibility/parameter-types.md
        - Extensibility/parameter-resolvers.md
        - Extensibility/middleware.md
        - Extensibility/interceptors.md 
        - Extensibility/token-transformations.md
      - test-tools.md
    - Release Notes:
      - ReleaseNotes/whats-new-in-v3.md
      - ReleaseNotes/CommandDotNet.md
      - ReleaseNotes/CommandDotNet.FluentValidation.md
      - ReleaseNotes/CommandDotNet.IoC.Autofac.md
      - ReleaseNotes/CommandDotNet.IoC.MicrosoftDependencyInjection.md
      - ReleaseNotes/CommandDotNet.IoC.SimpleInjector.md
      - ReleaseNotes/CommandDotNet.NameCasing.md
      - ReleaseNotes/CommandDotNet.TestTools.md
    - Roadmap: 
      - ReleaseNotes/roadmap.md
theme:
  features:
    - tabs
    - instant
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  favicon: 'img/favicon.ico'
  palette:
    primary: 'black'
    accent: 'red'  
  logo: 'img/small-logo.svg'

google_analytics:
  - 'UA-39358317-3'
  - 'auto'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.escapeall:
      nbsp: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
     permalink: "#"   

plugins:
  - search
  # - git-revision-date-localized

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/bilal-fazlani'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/bilal_fazlani'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/bilal-fazlani/'
